name: Npm Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/npm-publish.yml
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-publish.yml@npm-publish-4.0.0
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    with:
      build-command: |
        git config --global user.email "freephoenix888@gmail.com"
        git config --global user.name "freephoenix888"
        npm run library:build:dirty
      test-command: "echo 'Tests are temporarily disabled'"
      should-generate-documentation: true
      generate-documentation-command: |
        git config --global user.email "freephoenix888@gmail.com"
        git config --global user.name "freephoenix888"
        npm run documentation:generate
        
